### ISSUE TITLE
Ignore reporting when there're no tests yet

### ISSUE THREAD

**Issue by soid** [gschmidl/jacoco-gradle#1]
It would be nice to ignore report building if there are no tests yet.

Now it fails to build the project.

```
* Where:
Script '(...)/jacoco.gradle' line: 83

* What went wrong:
Execution failed for task ':test'.
> Unable to read execution data file (...)/build/tmp/jacoco/jacoco.exec
```

**Comment by adrianjgeorge** [comment]
I also have this problem.

**Comment by zzantozz** [comment]
I've forked, fixed, and sent a pull request for this issue. I hope it'll be merged soon. In the meantime, you can find a fixed version in [my fork](https://github.com/zzantozz/jacoco-gradle), or you can look at the [really simple fix](https://github.com/zzantozz/jacoco-gradle/commit/d91acfcb91beba61f4a80c2b8d132a2f37dba45e) and fork it yourself.

**Comment by gschmidl** [comment]
Thanks, I will gladly fix it once I'm back from holiday with very limited net access.

**Comment by gschmidl** [comment]
I hope this works now - thanks a lot, zzantozz.
