### ISSUE TITLE
gradle-jacoco-plugin created referencing jacoco-gradle

### ISSUE THREAD

**Issue by abirmingham** [gschmidl/jacoco-gradle#3]
Just wanted to let you know that I created a plugin using much of your code here. I did reference your work at the bottom of the plugin page. Please let me know if my copy/paste is a problem. In any case, I'd be eager to get your opinion on it at https://github.com/abirmingham/gradle-jacoco-plugin. Thanks for providing jacoco-gradle!

**Comment by gschmidl** [comment]
Hello Alex,

this is no problem whatsoever! I'm glad you found it useful.
