### ISSUE TITLE
Need to contact you somehow

### ISSUE THREAD

**Issue by sev-** [gschmidl/jacoco-gradle#6]
Hi, sorry for (ab)using the Issues. but I hope, this will reach you. I need your contact information in regards to getting access to the Steam release of the Full Pipe game, which you submitted to our bugtracker: https://bugs.scummvm.org/ticket/10569

Could you please drop me a line at sev@scummvm.org

**Comment by gschmidl** [comment]
Will e-mail you as soon as I've processed your request :)
